<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Codedge\Fpdf\Fpdf\Fpdf;   

class SmallBoatsPdf extends Controller
{ 
    public function small_boat_report(Fpdf $fpdf, Request $Request) { 
        $Checklist1a = \DB::table('checklist_1a')->where('Boat', $Request->Boat)->orderBy('Date', 'DESC')->orderBy('TimeIn')->first();
        $Checklist1b = \DB::table('checklist_1b')->where('Boat', $Request->Boat)->orderBy('Date', 'DESC')->orderBy('TimeIn')->first();
        $Checklist1c = \DB::table('checklist_1c')->where('Boat', $Request->Boat)->orderBy('Date', 'DESC')->orderBy('TimeIn')->first();
        $Checklist1d = \DB::table('checklist_1d')->where('Boat', $Request->Boat)->orderBy('Date', 'DESC')->orderBy('TimeIn')->first();
        $Checklist1e = \DB::table('checklist_1e')->where('Boat', $Request->Boat)->orderBy('Date', 'DESC')->orderBy('TimeIn')->first();
        $fpdf->AddPage();    
        // $fpdf->SetAutoPageBreak(false);
        $fpdf->SetFont('Arial', '', 10);  
 
        $Company = \DB::table('vessels_vessel_information')->select('Company')->where('VesselName', 'ASAGA')->first();  
        $fpdf->SetTitle('HANDOVER STATEMENT - ' . $Request->Boat);

        if($Company == null) {
            $fpdf->Image('../public/images/letter-head.png', 10, 7, 190);   
        } else if ($Company->Company == 'L.T.T') {
            $fpdf->Image('../public/images/letter-head.png', 10, 7, 190);    
        } else if ($Company->Company == 'DEPASA') {  
            $fpdf->Image('../public/images/depasa-letter-head.png', 10, 7, 190);    
        } 

        $fpdf->Ln(35);      
        
        $fpdf->SetFont('Arial', 'B', 15); 
        $fpdf->SetFillColor(217, 242, 255);  
        $fpdf->Cell(190, 10, 'SMALL BOATS, CAPTAINS & ENGINEERS HANDOVER STATEMENT', 0, 1, 1, 'L');
        $fpdf->Ln(5);      
        $fpdf->SetFillColor(255, 255, 255);  
        $fpdf->SetFont('Arial', 'B', 12); 

        $fpdf->Cell(38, 6, 'Port/Place of', 'LTR', 0, 'C');
        $fpdf->Cell(38, 12, 'Date', 'LTR', 0, 'C');
        $fpdf->Cell(38, 12, 'Boat', 'LTR', 0, 'C');
        $fpdf->Cell(38, 6, 'Outgoing Capt/', 'LTR', 0, 'C');
        $fpdf->Cell(38, 6, 'Incoming Capt/', 'LTR', 0, 'C');
        $fpdf->Ln();      
        $fpdf->Cell(38, 6, 'Handover', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, '', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, '', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, 'Eng. Name', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, 'Eng. Name', 'LBR', 0, 'C');
        $fpdf->Ln();      
        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(38, 6, $Checklist1a->Port_PlaceOfHandover ?? '-', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, $Checklist1a->Date ?? '-', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, $Checklist1a->Boat ?? '-', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, $Checklist1a->OutgoingCapt_EngName ?? '-', 'LBR', 0, 'C');
        $fpdf->Cell(38, 6, $Checklist1a->IncomingCapt_EngName ?? '-', 'LBR', 0, 'C');
        
        $fpdf->SetFont('Arial', 'B', 9); 
        $fpdf->Ln(12);      
        $fpdf->Cell(7, 10, 'No', 'LTR', 0, 'C');
        $fpdf->Cell(70, 10, 'Subject', 'LTR', 0, 'C');
        $fpdf->Cell(14, 10, 'Good', 'LTR', 0, 'C');
        $fpdf->Cell(14, 5, 'Not', 'LTR', 0, 'C');
        $fpdf->Cell(17, 5, 'Who to ', 'LTR', 0, 'C');
        $fpdf->Cell(68, 10, 'Comments', 'LTR', 1, 'C');
        $fpdf->Ln(-5);       
        $fpdf->Cell(91, 5, '', 'LBR', 0, 'C'); 
        $fpdf->Cell(14, 5, 'Good', 'LBR', 0, 'C');
        $fpdf->Cell(17, 5, 'fill in', 'LBR', 0, 'C');
        $fpdf->Cell(68, 5, '', 'LBR', 0, 'C');
        $fpdf->Ln();       
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '1', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'General(Clean & Tidy)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->Clean_Tidy ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->Clean_Tidy ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1a->Clean_Tidy_Comment ?? '-', 1, 1); 
                
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Communication (General)', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '2', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'VHF 1', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->VHF_1 ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->VHF_1 ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1a->VHF_1_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '3', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'VHF 2', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->VHF_2 ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->VHF_2 ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1a->VHF_2_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '4', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Handheld', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->Handheld ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->Handheld ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1a->Handheld_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '5', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'AIS', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->AIS ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1a->AIS ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1a->AIS_Comment ?? '-', 1, 1);
        $fpdf->SetFont('Arial', 'B', 12); 

                
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Corresponding/ Filling', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '6', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'SOP to date', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->SOPToDate ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->SOPToDate ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->SOPToDate_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '7', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Company orders to date', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->CompanyOrdersToDate ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->CompanyOrdersToDate ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->CompanyOrdersToDate_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '8', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Logbooks to date', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->LogbooksToDate ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->LogbooksToDate ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->LogbooksToDate_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '9', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Requisition book to date', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->RequisitionBookToDate ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->RequisitionBookToDate ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->RequisitionBookToDate_Comment ?? '-', 1, 1);

        $fpdf->Cell(7, 7, '10', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Pending requisitions (Name)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->PendingRequisutions_Name ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->PendingRequisutions_Name ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->PendingRequisutions_Name_Comment ?? '-', 1, 1); 
                
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Navigation & Electronic Equipment', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '11', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Magnetic compass', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->MagneticCompass ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->MagneticCompass ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->MagneticCompass_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '12', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Radar', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->Radar ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->Radar ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->Radar_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '13', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Echo sounder', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->EchoSounder ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->EchoSounder ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->EchoSounder_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '14', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'GPS', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->GPS ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->GPS ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->GPS_Comment ?? '-', 1, 1);
        $fpdf->SetFont('Arial', 'B', 12); 
        
                
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Deck Equipment', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '15', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Bits and Bollards', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->BitsAndBollards ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->BitsAndBollards ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->BitsAndBollards_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '16', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of ropes', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->ConditionOfRopes ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->ConditionOfRopes ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->ConditionOfRopes_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '17', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of windows', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->ConditionOfWindows ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->ConditionOfWindows ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->ConditionOfWindows_Comment ?? '-', 1, 1); 
 
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Hull (Dents and damages)', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '18', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Deck maintenance condition', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->DeckMaintenanceCondition ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->DeckMaintenanceCondition ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->DeckMaintenanceCondition_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '19', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Accommodation Maint. Condition', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->AccommodationMaintenanceCondition ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->AccommodationMaintenanceCondition ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->AccommodationMaintenanceCondition_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '20', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Pilot Handrails condition', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->PilotHandrailsCondition ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->PilotHandrailsCondition ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->PilotHandrailsCondition_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '21', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Tyre fender condition', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->TyreFenderCondition ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->TyreFenderCondition ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->TyreFenderCondition_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '22', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Hull fenders condition', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->HullFendersCondition ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->HullFendersCondition ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->HullFendersCondition_Comment ?? '-', 1, 1);
        $fpdf->SetFont('Arial', 'B', 12); 
        
                
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Environmental', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '23', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Garbage collecting', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->GarbageCollecting ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->GarbageCollecting ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->GarbageCollecting_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '24', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Garbage depositing', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->GarbageDepositing ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->GarbageDepositing ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->GarbageDepositing_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '25', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Engine smoking', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->EngineSmoking ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->EngineSmoking ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->EngineSmoking_Comment ?? '-', 1, 1); 
 
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Fire Equipment', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '26', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Extinguishers (exp. date)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->Extinguishers_Exp_Date ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->Extinguishers_Exp_Date ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->Extinguishers_Exp_Date_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '27', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Fire hoses (no condition)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->FireHosesCondition ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->FireHosesCondition ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->FireHosesCondition_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '28', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Nozzles (No condition)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->Nozzles_NoCondition ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->Nozzles_NoCondition ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->Nozzles_NoCondition_Comment ?? '-', 1, 1); 
 
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Safety Equipment (Condition)', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '29', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Life rafts and cradles', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->LifeRaftsAndCradles ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->LifeRaftsAndCradles ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->LifeRaftsAndCradles_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '30', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Life rings', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->LifeRings ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->LifeRings ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->LifeRings_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '31', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Life jackets and work vest', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->LifeJacketsAndWorkVest ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->LifeJacketsAndWorkVest ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->LifeJacketsAndWorkVest_Comment ?? '-', 1, 1); 
 
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Crew Presence on board', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '32', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'All crew on board', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->AllCrewOnBoard ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->AllCrewOnBoard ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->AllCrewOnBoard_Comment ?? '-', 1, 1); 
          
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Liquids on board', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '33', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Fuel oil (ROB)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->FuelOil ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->FuelOil ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->FuelOil_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '34', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Lube oil (ROB)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->LubeOil ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->LubeOil ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->LubeOil_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '35', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Fresh water (ROB)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->FreshWater ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->FreshWater ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->FreshWater_Comment ?? '-', 1, 1); 
 
        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Engine Maintenance ', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '36', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of main engine(s)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfMainEngine ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfMainEngine ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->ConditionOfMainEngine_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '37', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Lube oil cons/hour/engine', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->LubeOil_Cons_hour_Engine ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->LubeOil_Cons_hour_Engine ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->LubeOil_Cons_hour_Engine_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '38', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of gear box(es)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfGearBox ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfGearBox ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->ConditionOfGearBox_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '39', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of gen set(s)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfGenSet ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfGenSet ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->ConditionOfGenSet_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '40', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of Bilge Pump', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfBilgePump ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1d->ConditionOfBilgePump ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1d->ConditionOfBilgePump_Comment ?? '-', 1, 1); 


        $fpdf->Cell(7, 7, '41', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of Bilge system', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->ConditionOfBilgeSystem ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->ConditionOfBilgeSystem ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->ConditionOfBilgeSystem_Comment ?? '-', 1, 1); 
 
        $fpdf->Cell(7, 7, '42', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Condition of Battery(es)', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->ConditionOfBattery ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->ConditionOfBattery ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->ConditionOfBattery_Comment ?? '-', 1, 1); 
 
        $fpdf->Cell(7, 7, '43', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Shore connection cables', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->ShoreConnectionCables ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1e->ShoreConnectionCables ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1e->ShoreConnectionCables_Comment ?? '-', 1, 1); 


        $fpdf->SetFont('Arial', 'B', 12); 
        $fpdf->Cell(190, 7, 'Safety of Navigation', 1, 1, 'C');
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->Cell(7, 7, '44', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Steering System', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->SteeringSytem ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->SteeringSytem ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->SteeringSytem_Comment ?? '-', 1, 1); 
         
        $fpdf->Cell(7, 7, '45', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Emergency Steering', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->EmergencySteering ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->EmergencySteering ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->EmergencySteering_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '46', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Navigational Lights', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->NavigationalLights ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->NavigationalLights ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->NavigationalLights_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '47', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Search Light', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->SearchLight ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->SearchLight ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->SearchLight_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '48', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'A and B Flags', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->A_B_Flags ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1b->A_B_Flags ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1b->A_B_Flags_Comment ?? '-', 1, 1); 

        $fpdf->Cell(7, 7, '49', 1, 0, 'C');
        $fpdf->Cell(70, 7, 'Siren/ Horn', 1, 0);
        $fpdf->Cell(14, 7, '', 1, 0);
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(89);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->Siren_Horn ?? '-' == 'Good' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(101);  
        $fpdf->Cell(14, 7, '', 1, 0); 
        $fpdf->SetY($fpdf->GetY() + 1);
        $fpdf->SetX(103);   
        $fpdf->SetFont('Courier', '', 18);
        $fpdf->Cell(10, 5, $Checklist1c->Siren_Horn ?? '-' == 'NotGood' ? '*' : '', 1, 0, 'C'); 
        $fpdf->SetFont('Arial', '', 9); 
        $fpdf->SetY($fpdf->GetY() - 1);
        $fpdf->SetX(115);  
        $fpdf->Cell(17, 7, 'Capt/Eng', 1, 0, 'C');
        $fpdf->Cell(68, 7, $Checklist1c->Siren_Horn_Comment ?? '-', 1, 1);
        $fpdf->SetFont('Arial', 'B', 9); 
        
        $fpdf->Ln(15); 
        $fpdf->Cell(68, 7, 'The service on the Vessel has been taken over in accordance with the above findings and comments', 0, 1);
        $fpdf->Ln();
        $fpdf->Cell(94, 7, 'Outgoing Captain /Engineer comments (If any): ', 'LTR', 0);
        $fpdf->Cell(94, 7, 'Incoming Captain/Engineer comments (If any): ', 'LTR', 1);
        $fpdf->Cell(94, 25, $Checklist1e->Outgoing_Captain_Engineer ?? '-', 'LBR', 0);
        $fpdf->Cell(94, 25, $Checklist1e->Incoming_Captain_Engineer ?? '-', 'LBR', 1);
         
        $fpdf->Cell(94, 7, 'Outgoing Captain /Engineer signature: ', 'LTR', 0);
        $fpdf->Cell(94, 7, 'Incoming Captain/Engineer signature: ', 'LTR', 1);
        $fpdf->Cell(94, 25, '', 'LBR', 0);
        $fpdf->Cell(94, 25, '', 'LBR', 1);

        $fpdf->Ln(15);

        $fpdf->Cell(188, 5, '...........................................................', 0, 1, 'R');
        $fpdf->Cell(188, 5, 'Confirmed by Operations Manager', 0, 1, 'R');

        $fpdf->Output();        
        exit; 
    }
}
