<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Codedge\Fpdf\Fpdf\Fpdf;   

class SpeedBoatsPdf extends Controller
{ 
    public function speed_boat_report(Fpdf $fpdf, Request $Request) {  
        $fpdf->AddPage();    
        // $fpdf->SetAutoPageBreak(false);
        $fpdf->SetFont('Arial', '', 10);  
 
        $Company = \DB::table('vessels_vessel_information')->select('Company')->where('VesselName', 'ASAGA')->first(); 
        $Month = strtoupper(\Carbon\Carbon::create()->month('11')->format('F'));
        $Year = '2024';
        $fpdf->SetTitle('Vessel Availabilty Report - ' . $Month . ' ' . $Year);

        if($Company == null) {
            $fpdf->Image('../public/images/ltt-letter-head.png', 10, 7, 190);   
        } else if ($Company->Company == 'L.T.T') {
            $fpdf->Image('../public/images/ltt-letter-head.png', 10, 7, 190);    
        } else if ($Company->Company == 'DEPASA') {  
            $fpdf->Image('../public/images/depasa-letter-head.png', 10, 7, 190);    
        } 

        $fpdf->Ln(35);      
        
        $fpdf->SetFont('Arial', 'B', 15); 
        $fpdf->SetFillColor(217, 242, 255);  
        $fpdf->Cell(190, 10, 'SPEED BOAT TECHNICAL CHECKLIST', 0, 1, 1, 'L');
        $fpdf->SetFont('Arial', '', 10);   

        $fpdf->Ln(6);     

        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(20, 0, 'BOAT NAME: ');
        $fpdf->SetFont('Arial', '', 7); 
        $fpdf->Cell(108.5, 0, 'ASAGA');
        $fpdf->SetFont('Arial', 'B', 7);  
        $fpdf->Ln(6);     

        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(20, 0, 'MONTH: ');   
        $fpdf->SetFont('Arial', '', 7); 
        $fpdf->Cell(108.5, 0, 'OCTOBER');

        $fpdf->SetDrawColor(200, 200, 200);
        $fpdf->SetTextColor(50, 50, 50);

        $fpdf->Ln(6);     

        $fpdf->SetFont('Arial', 'B', 9); 
        $fpdf->Cell(8, 6, '');
        $fpdf->Cell(113.5, 5, '');
        $fpdf->Cell(17, 6, 'WK 44', 1, 0, 'C');
        $fpdf->Cell(17, 6, 'WK 45', 1, 0, 'C');
        $fpdf->Cell(17, 6, 'WK 46', 1, 0, 'C');
        $fpdf->Cell(17, 6, 'WK 47', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 6, 'S/N', 1);
        $fpdf->Cell(113.5, 6, 'CHECK AREAS', 1, 0, 'C');
        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(8.5, 6, 'OK', 1, 0, 'C');
        $fpdf->Cell(8.5, 6, 'BAD', 1, 0, 'C');
        $fpdf->Cell(8.5, 6, 'OK', 1, 0, 'C');
        $fpdf->Cell(8.5, 6, 'BAD', 1, 0, 'C');
        $fpdf->Cell(8.5, 6, 'OK', 1, 0, 'C');
        $fpdf->Cell(8.5, 6, 'BAD', 1, 0, 'C');
        $fpdf->Cell(8.5, 6, 'OK', 1, 0, 'C');
        $fpdf->Cell(8.5, 6, 'BAD', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 6, '1', 1);
        $fpdf->SetFont('Arial', 'B', 9); 
        $fpdf->Cell(113.5, 6, 'ENGINE AND FUEL SYSTEM', 0, 0);
        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 6, '', 0, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Throttle cable and steering condition ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Trim of engine condition ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Fuel and water lines connection for leaks ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Test engine kickstart  ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Transmission Lubricant level ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Cooling system (Water intake and discharge) ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Engine, transom and Centre drain plugs ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Fuel filters ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Oil Pressure  ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Bilge pumps ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Shifting Linkage ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Guage system ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Propeller condition ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Hydraulic system ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Engine spark plug ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');

        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '2', 1);
        $fpdf->SetFont('Arial', 'B', 9); 
        $fpdf->Cell(113.5, 5, 'ELECTRICAL SYSTEM', 0, 0);
        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'All electronics working (Lights, depth finder, chart plotter, GPS) ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Wired terminals and connection  ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Circuit breakers and fuses ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Navigation and anchor Light  ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Flood and cabin light', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Battery head connection ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Horn ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C'); 
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '3', 1);
        $fpdf->SetFont('Arial', 'B', 9); 
        $fpdf->Cell(113.5, 5, 'BOAT HULL, ANCHOR AND OTHERS', 0, 0);
        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 0, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Anchor properly stowed and in good condition ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Bits and upholstery ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Mooring lines and fender condition ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Fire extinguishers and fire blanket', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Hull condition', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Tool kits status', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Boat Hook and Paddle', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Life jacket condition ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Ln(); 
        $fpdf->Cell(8, 5, '', 1);
        $fpdf->SetFont('Arial', '', 8); 
        $fpdf->Cell(113.5, 5, 'Ladder  ', 1, 0); 
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C');
        $fpdf->Cell(8.5, 5, '', 1, 0, 'C'); 

        $fpdf->Ln(15); 

        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(25, 0, 'TECHNICAL: ');
        $fpdf->SetFont('Arial', '', 7); 
        $fpdf->Cell(108.5, 0, '______________________________');
        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(15, 0, 'SIGNED: ');
        $fpdf->SetFont('Arial', '', 7); 
        $fpdf->Cell(10, 0, '______________________________');
        $fpdf->Ln(6);     

        $fpdf->SetFont('Arial', 'B', 7); 
        $fpdf->Cell(25, 0, 'BOAT SKIPPER: ');
        $fpdf->SetFont('Arial', '', 7); 
        $fpdf->Cell(108.5, 0, '______________________________'); 

        $fpdf->Output();        
        exit; 
    }
}
